/* FACTS
   One of these is shown at random once the intro puzzle is solved.
   Plain sentences, no HTML, no em dashes. Add or remove freely: the gate
   picks one from however many are in this list.

   Edit this file, then run `npm run build`. */

module.exports = [
  "A pipeline that runs is not the same as a pipeline that is correct. Most data outages are completely silent.",
  "Idempotency is the most valuable property a batch job can have. It turns a 3am failure into a retry.",
  "Parquet compresses better than CSV because values within a column resemble each other far more than values within a row.",
  "Predicate pushdown lets a query skip whole chunks of a Parquet file without ever decompressing them.",
  "Bronze, silver, gold is really just: keep the raw bytes, keep the cleaned version, keep the version people query.",
  "If you cannot replay last March, you do not have a pipeline. You have a cron job.",
  "Late-arriving data is why Monday's number changes on Wednesday.",
  "A type-2 slowly changing dimension keeps history by adding rows, never by overwriting them.",
  "Airflow schedules the end of an interval, which is why your Monday DAG runs on Tuesday.",
  "Exactly-once delivery is usually at-least-once delivery plus idempotent writes.",
  "The most expensive query in most warehouses is the one nobody remembers scheduling.",
  "Partitioning speeds up reads by letting the engine ignore files. Over-partitioning slows it down by making it open thousands of tiny ones.",
  "A data contract is just a schema plus a promise about who gets told before it changes.",
  "Column pruning often saves more compute than any index you could add.",
  "Incremental models exist because recomputing history every night is a way of paying for the same answer repeatedly.",
  "Most 'real-time' requirements turn out to be 'before the 9am meeting' requirements.",
  "Schema drift rarely breaks a pipeline loudly. It usually just starts producing nulls.",
  "Change data capture reads the database's own write-ahead log, which is why it can track deletes that a nightly snapshot would miss.",
  "Orchestration is not scheduling. Scheduling starts things; orchestration knows what to do when one of them fails.",
  "Dead-letter queues are an admission that some records will always be unprocessable, and that this is fine.",
  "Small-file problems are the most common cause of a slow lakehouse.",
  "A denormalised table is a cache. Like every cache, its hardest problem is invalidation.",
  "The lakehouse exists because people wanted warehouse transactions on object storage prices.",
  "Data lineage matters most on the day someone asks why a number moved and everyone points at someone else.",
  "Great Expectations, dbt tests and schema checks all do the same thing: fail loudly before a human quietly trusts the wrong number.",
  "Backpressure is a system telling you it is being asked for more than it can deliver. Ignoring it turns latency into data loss.",
  "Streaming is not faster batch. It is a different consistency model with different failure modes.",
  "Watermarks in stream processing are a bet about how late 'late' can get.",
  "Star schemas persist because humans reason about facts and dimensions more easily than about normalised graphs.",
  "Query cost and query latency are different problems, and optimising one often worsens the other.",
  "Leakage is rarely correlation between features and target. It is usually correlation between features and time.",
  "A model that beats baseline by 1% can still lose in production if it is ten times harder to maintain.",
  "Class imbalance is not a flaw in your data. It is a property of it. The flaw is measuring with accuracy.",
  "AUC measures ranking, not calibration. A model can rank perfectly and still say 90% when it means 40%.",
  "Cross-validating time series without respecting time order gives you a number you will never reproduce.",
  "Feature engineering is mostly the act of giving a model information it could not have derived on its own.",
  "The single best predictor of a model's production performance is how similar production data is to training data.",
  "Regularisation is a statement about what you believe before seeing the data.",
  "A confusion matrix tells you more in four numbers than accuracy does in one.",
  "Precision and recall trade off because the threshold is a business decision disguised as a hyperparameter.",
  "Gradient boosting builds each tree to correct the previous one's mistakes, which is why it overfits quietly if you let it.",
  "Random forests reduce variance by decorrelating trees. Boosting reduces bias by stacking them.",
  "The bias–variance decomposition explains why the most flexible model is often not the best one.",
  "SHAP values come from cooperative game theory: they distribute a prediction among features the way you would split a payout among players.",
  "Feature importance from a tree model tells you what it used, not what matters.",
  "Hyperparameter search is cheap compared to the cost of a model that is wrong in a way nobody notices.",
  "A calibrated model is one whose 70% actually happens about 70% of the time. Most models are not calibrated by default.",
  "Optuna and similar tools prune bad trials early, which is usually worth more than a smarter search strategy.",
  "Concept drift is the world changing. Data drift is your inputs changing. They need different responses.",
  "Retraining on a schedule is a guess. Retraining on a drift signal is a decision.",
  "Stratified splitting matters most exactly when your classes are most imbalanced.",
  "The test set is only a test set the first time you look at it.",
  "MLflow exists because 'which run produced this model' is a question that always gets asked eventually.",
  "Ensembles usually win because their errors are uncorrelated, not because their members are strong.",
  "ARIMA is still competitive on many forecasting problems, which says more about forecasting than about ARIMA.",
  "Seasonality, trend and residual is a decomposition, not an explanation.",
  "A baseline that predicts 'the same as last week' beats a surprising number of forecasting models.",
  "Missing data is information. Imputing it silently discards that information.",
  "Target encoding leaks unless you compute it inside the cross-validation fold.",
  "Normalising your features changes nothing for tree models and everything for gradient-based ones.",
  "The universal approximation theorem says one hidden layer can approximate any continuous function. It says nothing about how many neurons you'd need, or whether you could train it.",
  "Dropout works partly because it approximates training an ensemble of exponentially many thinner networks.",
  "Batch normalisation was explained as reducing internal covariate shift. Later work suggests it mostly smooths the loss landscape.",
  "Residual connections let gradients flow straight backwards, which is why networks suddenly got much deeper.",
  "Attention is a learned soft lookup: a query, a set of keys, and the values they point at.",
  "Self-attention is quadratic in sequence length, which is the whole reason long-context research exists.",
  "A transformer has no inherent sense of order. Positional encoding is what supplies it.",
  "Convolution is weight sharing plus locality. That inductive bias is why CNNs need less data than dense networks for images.",
  "Pooling throws away spatial precision in exchange for translation tolerance.",
  "Transfer learning works because early layers learn edges and textures, which are the same in almost every image dataset.",
  "Fine-tuning changes all weights. LoRA changes a low-rank approximation of them, which is why it fits in far less memory.",
  "Quantisation trades precision for memory. Most networks tolerate it surprisingly well.",
  "A GAN is two networks with opposing objectives, which is why training it is a stability problem before it is an accuracy problem.",
  "Mode collapse is a generator finding one output that reliably fools the discriminator, and then never leaving.",
  "CycleGAN can translate between image domains without paired examples, which is why it is useful for synthetic data.",
  "Vanishing gradients are why sigmoid activations fell out of favour in deep stacks.",
  "ReLU is popular partly because its derivative is either zero or one, which is cheap and numerically stable.",
  "Learning rate is the hyperparameter most likely to be the reason your model is not training.",
  "Warmup exists because large batches early in training produce gradients that are confidently wrong.",
  "Early stopping is regularisation that costs nothing.",
  "Data augmentation is a way of telling a model which transformations should not change its answer.",
  "A deep network with enough capacity can memorise random labels. Generalisation is therefore not explained by capacity alone.",
  "Embeddings are just learned coordinates where distance means something useful.",
  "Cosine similarity ignores magnitude, which is usually what you want when comparing embeddings.",
  "ONNX exists so the framework you trained in does not have to be the framework you deploy in.",
  "A language model predicts the next token. Everything else it appears to do is a consequence of doing that well.",
  "Tokens are not words. 'Tokenisation' is itself several tokens.",
  "Temperature does not control correctness. It controls how much probability mass below the top choice gets a say.",
  "Temperature zero is not deterministic across different hardware, batch sizes or model versions.",
  "Context windows grew faster than the ability to use them well. Information in the middle is often attended to least.",
  "A hallucination is not a bug in the sampling. It is the model doing exactly what it was trained to do with insufficient grounding.",
  "Instruction tuning is what turned text completers into things you can ask questions.",
  "RLHF optimises for what human raters preferred, which is not always the same as what is true.",
  "A system prompt is just tokens. It has no special privilege the model is obliged to respect.",
  "Prompt injection works because models cannot reliably distinguish instructions from data in a single stream of text.",
  "Few-shot examples often outperform a longer instruction, because they demonstrate the format instead of describing it.",
  "Chain of thought helps on problems where intermediate steps reduce the difficulty of each next token.",
  "Structured output beats free text whenever something downstream has to parse it.",
  "Evaluating a generative model is harder than training one, because there is rarely a single correct answer.",
  "LLM-as-judge is useful and biased. It tends to prefer longer answers and its own style.",
  "Distillation trains a small model on a large model's outputs, trading some capability for a great deal of speed.",
  "Mixture-of-experts models activate only a fraction of their parameters per token, which is how parameter count and inference cost decoupled.",
  "KV caching is why the second token of a response arrives far faster than the first.",
  "Speculative decoding uses a small model to guess ahead and a large one to check, which is faster than the large model alone.",
  "Running a model locally costs nothing per request. That changes which architectures make economic sense.",
  "RAG exists because context windows are finite and retraining is expensive. Both constraints keep moving.",
  "In RAG, retrieval sets the ceiling. A perfect model cannot answer from a chunk it never saw.",
  "Chunking strategy usually matters more than which embedding model you picked.",
  "Chunk overlap exists so a sentence split across a boundary is still findable from either side.",
  "A bi-encoder embeds query and document separately, so documents can be indexed in advance.",
  "A cross-encoder reads query and document together, which is far more accurate and impossible to pre-index.",
  "Two-stage retrieval is the compromise: cheap recall first, expensive precision second.",
  "Hybrid search combines keyword and vector retrieval because exact terms and semantic similarity fail in different ways.",
  "HNSW trades a little recall for a very large speedup by searching a navigable graph instead of every vector.",
  "Approximate nearest neighbour search is approximate on purpose. Exact search does not scale.",
  "Embedding a question and embedding an answer place them in different regions, which is why some systems embed hypothetical answers instead.",
  "Re-embedding your whole corpus is the real cost of changing embedding model.",
  "Citations are not decoration. They are the only way a reader can check a generated claim.",
  "Grounding means the answer is constructed from retrieved text, not merely accompanied by it.",
  "The hardest RAG failure is the confident answer assembled from three chunks that were each about something else.",
  "An agent is mostly a loop: call the model, run the tool it asked for, feed the result back, repeat.",
  "The hard part of agents is not calling tools. It is knowing when to stop.",
  "Every additional autonomous step multiplies the probability of compounding error.",
  "A tool description is a prompt. Ambiguity in it becomes wrong tool calls.",
  "MCP, the Model Context Protocol, standardises how an application exposes tools, resources and prompts to a model, so every integration stops being bespoke.",
  "Human-in-the-loop is not a fallback for weak models. It is a design choice about where accountability sits.",
  "An agent that can retry is more useful than an agent that is right the first time but cannot recover.",
  "State machines beat free-form agent loops whenever the set of valid next steps is actually known.",
  "Auditability means being able to answer 'why did it do that' after the fact, not during.",
  "Confidence thresholds that route uncertain cases to a person are usually worth more than a few points of accuracy.",
  "Guardrails belong before the action, not after the output.",
  "The cost of an agent is the sum of every token it spent deciding, not just the ones you read.",
  "Tool calling is structured output with consequences.",
  "Giving a model fewer tools usually improves its tool selection more than describing the tools better.",
  "An agent with memory is a distributed system, with all the consistency problems that implies.",
  "Most production machine learning is data engineering wearing a different job title.",
  "The model is usually the smallest part of a machine learning system, by both code and effort.",
  "Technical debt in ML accumulates in the data, not only in the code.",
  "Reproducibility requires pinning the data as well as the seed.",
  "A dashboard nobody opens is a pipeline nobody needed.",
  "Shadow deployment tells you how a model would have behaved without letting it affect anything.",
  "A/B tests measure what happened. They do not explain it.",
  "Simpson's paradox means a trend can reverse when you split the data, and both versions are arithmetically correct.",
  "p-hacking is not usually deliberate. It is what happens when you test until something is significant.",
  "Survivorship bias is the reason the plane armour goes where the returning planes were not hit.",
  "Goodhart's law: when a measure becomes a target, it stops being a good measure.",
  "The base rate is the most commonly ignored number in applied statistics.",
  "Correlation does not imply causation, but it is a very good reason to go looking.",
  "A confidence interval is a statement about the procedure, not about the parameter.",
  "Anscombe's quartet: four datasets with identical summary statistics and completely different shapes.",
  "Always plot the data. Summary statistics conceal exactly what you most need to see."
];
